name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  setup_and_build:
    runs-on: macos-15-intel
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout Books
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn

      - name: Run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          APPLE_NOTARIZE: 0
        run: yarn build -mw --publish never
